### ISSUE TITLE
Consider renaming to docs.moja.global

### ISSUE THREAD

**Issue by abhineet97** [moja-global/GSoD.moja_global_docs#14]
Hi, @Tlazypanda.

The presence of _readthedocs.io_ at the end already implies the nature of the website, so the "documentation" part in the current name --- _moja-global-documentation_.readthedocs.io --- seems unnecessary.

What are your thoughts on using _moja-global_.readthedocs.io, instead?

**Comment by gmajan** [comment]
@abhi211199 Thank you for this suggestion. I think we can consider it after we have completed the documentation as we do not want to lose time now with downloading and uploading the documentation. We can do that when we have less time pressure. Would you agree?
I also think that not everybody might understand that readthedocs is the documentation. So I will cautiously check with a few non-coders which name is better.
thx again. More soon.

**Comment by aornugent** [comment]
Following readthedocs own example `docs.moja.global` would be the most succinct. SEO is important: https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html

**Comment by abhineet97** [comment]
Great suggestion @aornugent. Renaming the issue to incorporate it.

Thanks!

**Comment by aornugent** [comment]
@abhineet97 has helpfully dug out the steps required to configure a custom domain :
- add a `docs.moja.global` CNAME record to the DNS service of `moja.global`
- add the new domain under the `readthedocs.io` Admin panel -> Domains

This would also enable sub-projects (e.g. `docs.moja.global/projects/reporting` or `docs.moja.global/projects/taswira`) in the future.

[1] https://docs.readthedocs.io/en/stable/custom_domains.html
[2] https://docs.readthedocs.io/en/stable/subprojects.html)

**Comment by gmajan** [comment]
Thank you Abhineet. Well done.

**Comment by gmajan** [comment]
The owner of our domain is The Linux Foundation. Shall I connect you to the IT person who can update our DNS? They don't share access to our registrar due to security reasons.

**Comment by abhineet97** [comment]
There's only one thing that's required. I think we can get it done in one go without much back and forth.

We need them to add the following record to the domain:
```
CNAME    docs.moja.global    readthedocs.io
```

**Comment by gmajan** [comment]
I have asked for the lines to be added. I will let you know when it is done.

**Comment by gmajan** [comment]
I has been added!

**Comment by Tlazypanda** [comment]
https://docs.moja.global/en/latest/ - Done :heavy_check_mark:
