### ISSUE TITLE
Order of Contributing TOC

### ISSUE THREAD

**Issue by aornugent** [moja-global/GSoD.moja_global_docs#19]
**What does the current documentation state?**
The Contributing section has six sub-topics in the TOC, but many of them are included in the top-level page `contributing/index.html`. If I navigate through the topics using the `Next` button, it jumps from `Ways to contribute to moja global` to the next topic `Github Workflow Best Practices` and skips three sub-topics.

**Where is this stated?**
https://moja-global-documentation--17.org.readthedocs.build/en/17/contributing/index.html

**Why do you want to improve the statement?**
Having the index match the navigation flow throught the documentation makes it easy to understand what is coming next.

**Proposed statement**
I think the `Before making a contribution`, `After making your first contribution` and `Non-code contributions to moja global` could be remove from `contributing/index.html` and left as separate sub-topics. 

What do you think?

**Comment by Tlazypanda** [comment]
Hey @aornugent Thanks for reviewing this :tada:  This is a common problem with reST toctree :sweat_smile: I have modified the pull request and drawn these out as separate sections :v: Thank you for your patience with me !!

**Comment by Tlazypanda** [comment]
Closed via #17
